name: test
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2
  
dependencies:

  flutter_svg: ^2.0.9

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^13.0.0
  pdfx: ^2.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  web : ^0.5.1
  http: ^0.13.6
  provider: ^6.1.1
  flutter_spinkit: ^5.2.0
  #
  webview_flutter: ^4.2.2
  shamsi_date: ^0.16.0
  url_launcher: ^6.2.5
  dropdown_button2: ^2.3.9
  graphview: ^1.2.0



  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/pictures/
    - assets/pictures/flags/
    - assets/graph.html
    - assets/sso-help.pdf

  fonts:
  - family: IranSans
    fonts:
      - asset: assets/fonts/IRANSansWeb_Bold.woff2
        weight: 700
      - asset: assets/fonts/IRANSansWeb_Medium.woff2
        weight: 500
      - asset: assets/fonts/IRANSansWeb.woff2
        weight: 400
